BDNS_Abbreviations_Register.csv

As per this issue https://github.com/theodi/BDNS/issues/66
Let me know if you have any comments happy to update the request.

add battery

---

.gitignore
BDNS_Governance_model.md

Some changes to the governance model document to be discussed at the next BDNS call on 2021-11-17.

Governance model update

---

BDNS_Abbreviations_Register.csv

Addition of moisture content sensor

MCS addition

---

BDNS_Abbreviations_Register.csv

DXC addition

---

BDNS_Abbreviations_Register.csv

WNG and VEND

---

BDNS_Abbreviations_Register.csv

added additional heat pump sub-types

---

BDNS_Abbreviations_Register.csv

Addition of new food equipment abbreviations and minor changes to descriptions (electrical->electric and omission of plurals)

food equipment and minor changes to descriptions

---

.github/workflows/github-actions-check.yml
tools/check-duplicates.py
tools/requirements.txt
tools/test/abbreviations.csv

Adding a github action checking workflow.
At the moment the only supported check is a check for duplicates of abbreviations.

Checking workflow

---

BDNS_Abbreviations_Register.csv

Removal of WDR and addition of HIU to check automatic duplicate checking

removed duplicate WDR + addition of HIU

---

BDNS_Abbreviations_Register.csv

Consolidating changes in previous PRs #112 and #121

sorting pull requests 112 and 121

---

BDNS_Abbreviations_Register.csv

added HVRF

---

BDNS_Abbreviations_Register.csv

Differential pressure switch typically used for runstatus and filter status

Adding differential Pressure Switch

---

BDNS_Abbreviations_Register.csv
BDNS_Specification_naming_syntax.md

Inclusion of PFC, GENCP, BUFF, HBUFF, CBUFF, PF
Removal of size specification for QR code

new abbreviations and removed size from QR code

---

BDNS_Abbreviations_Register.csv

addition of FPB

---

BDNS_Abbreviations_Register.csv

pull request for adding MVHR and MEV. 
I added MVHR to the "air handling" section, but added MEV to the "fan" section as this felt most appropriate. 
Note that the rows are approx. ordered by `asset_description` but not quite. 
Please edit as you see fit. 
many thanks

add mvhr and mev

---

BDNS_Abbreviations_Register.csv

added Motorised Smoke Control Damper (MSCD)
https://github.com/theodi/BDNS/issues/149

149 add MSCD

---

BDNS_Abbreviations_Register.csv

this closes:
https://github.com/theodi/BDNS/issues/123

123-Abbreviations-for-electrical-distribution-2

---

BDNS_Abbreviations_Register.csv
tools/test/abbreviations.csv

closes:
https://github.com/theodi/BDNS/issues/46
like:
https://github.com/theodi/BDNS/pull/165/commits/ea253424270596cec1d3be3e7c4e3c287d6bdc4b
but without the sorting!

46-socket-outlets-attempt-3

---

BDNS_Abbreviations_Register.csv

closes https://github.com/theodi/BDNS/issues/173

✨ added BCBOX BSBOX. note, their function is the same but terminology differes across main brands. both included to avoid confusion.

---

BDNS_Abbreviations_Register.csv

closes https://github.com/theodi/BDNS/issues/132

132-Emergency-Voice-Communication

---

BDNS_Abbreviations_Register.csv

closes https://github.com/theodi/BDNS/issues/168

✨ added DWCCP DWCOI DWCPC DWCRB (disabled toilet emergency assistance)

---

BDNS_Abbreviations_Register.csv

closes https://github.com/theodi/BDNS/issues/172

✨ added CABASK CALAD CATR CATRK CAFTRK

---

BDNS_Abbreviations_Register.csv

closes 
https://github.com/theodi/BDNS/issues/159
1 remaining question is whether `shading device control panel` is required in addition to `shading device controller` ? it is currently not added in this PR

159-shading-devices

---

BDNS_Abbreviations_Register.csv

closes https://github.com/theodi/BDNS/issues/181

181-lighting-fitting-type-abbreviations

---

BDNS_Abbreviations_Register.csv

✨ added bag and panel filters: BFLT, PFLT

---

BDNS_Abbreviations_Register.csv

➕ added AVFS, WVFS. ran sort script

---

BDNS_Abbreviations_Register.csv

this closes out https://github.com/theodi/BDNS/issues/190

✨ add AT for air terminal

---

BDNS_Abbreviations_Register.csv

adds the agreed upon abbreviations from #111

Add-CFLT,-EMDH,-MLOCK

---

BDNS_Abbreviations_Register.csv

closes https://github.com/theodi/BDNS/issues/191

➕ UFM - underfloor manifold

---

BDNS_Abbreviations_Register.csv

closes https://github.com/theodi/BDNS/issues/198

➕ LSW - lighting control switch

---

BDNS_Abbreviations_Register.csv

closes https://github.com/theodi/BDNS/issues/199

➕ DIM - lighting control dimmer

---

BDNS_Abbreviations_Register.csv

➕ ADS - air and dirt separator

---

BDNS_Abbreviations_Register.csv

➕ add CU (consumer unit distribution board)

---

BDNS_Abbreviations_Register.csv

➕ add MD - motorised damper

---

BDNS_Abbreviations_Register.csv

➕ add BTR battery trip unit

---

BDNS_Abbreviations_Register.csv

add CRAH abbreviation for Computer Room Air Handler
issue #214

add CRAH abbreviation

---

BDNS_Abbreviations_Register.csv

➕added RTE request to exit button

---

BDNS_Abbreviations_Register.csv

➕ CAST (compressed air storage tank)

---

BDNS_Abbreviations_Register.csv

Added VIC (Video) and AIC (Audio) Intercom

Update BDNS_Abbreviations_Register - Added VIC and AIC Intercom

---

BDNS_Abbreviations_Register.csv

263-tanks-refactor

---

BDNS_Abbreviations_Register.csv

addition of room controller ROC

---

BDNS_Abbreviations_Register.csv

As per discussion in https://github.com/theodi/BDNS/issues/313

Add EMV, GMV, HMV and WMV virtual metering asset types

---

BDNS_Abbreviations_Register.csv

➕ VBS vibration sensor

---

BDNS_Abbreviations_Register.csv

➕add air terminal types

---

BDNS_Abbreviations_Register.csv

➕ring main unit - RMU

---

BDNS_Abbreviations_Register.csv

➕add chilled beams and chilled ceiling

---

BDNS_Abbreviations_Register.csv

➕ add INSO - Industrial Socket Outlet

---

BDNS_Abbreviations_Register.csv

Fixing typos and aligning to IFC 2x3 in relation to issue #355

alignment with IFC 2x3

---

BDNS_Abbreviations_Register.csv

Additional changes to align to IFC 2x3 in relation to our discussion in [this spreadsheet](https://docs.google.com/spreadsheets/d/1VBIum9MpiLeNh61-9Ai1yH9kgwSEEyaeHGSUsya38b8/edit?pli=1&resourcekey=0-AyFuW9rxezlHV12XDBpKZg&gid=896113606#gid=896113606)

IFC 2x3 alignment - continued
